version: '3'

services:
  backend:
    build: 
      context: ../klonx
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=your-access-key
      - MINIO_SECRET_KEY=your-secret-key
      - PYTHONUNBUFFERED=1
    depends_on:
      - minio
    volumes:
      - ../klonx:/app

  frontend:
    build: 
      context: ../klonx-vue
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../klonx-vue:/app

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=your-access-key
      - MINIO_SECRET_KEY=your-secret-key
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data

volumes:
  minio-data:
